# Generated by Django 4.2.26 on 2025-11-05 22:47

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_sensordefinition_sensor_code_sensorreading'),
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('member_id', models.CharField(max_length=100, unique=True)),
                ('name', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='notificationlog',
            name='alert_rule',
        ),
        migrations.RemoveIndex(
            model_name='sensorreading',
            name='core_sensor_sensor__6f9b81_idx',
        ),
        migrations.RenameField(
            model_name='errorreport',
            old_name='description',
            new_name='detail',
        ),
        migrations.AddField(
            model_name='errorreport',
            name='abstract',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='errorreport',
            name='generated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='errorreport',
            name='raw_xml',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='sensor',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='sensor',
            name='type',
            field=models.CharField(default='measured', max_length=50),
        ),
        migrations.AlterField(
            model_name='sensordefinition',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),

        # --- AGREGAR LOS CAMPOS device ANTES DE CREAR LOS INDICES ---
        migrations.AddField(
            model_name='errorreport',
            name='device',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='errors', to='core.device'),
        ),
        migrations.AddField(
            model_name='sensor',
            name='device',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sensors', to='core.device'),
        ),
        migrations.AddField(
            model_name='sensorreading',
            name='device',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='readings', to='core.device'),
        ),

        # Ahora sí: añadir los índices (campo device ya existe en el estado)
        migrations.AddIndex(
            model_name='errorreport',
            index=models.Index(fields=['device', 'error_code', 'reported_at'], name='core_errorr_device__7d4d4e_idx'),
        ),
        migrations.AddIndex(
            model_name='sensorreading',
            index=models.Index(fields=['device', 'sensor', 'received_at'], name='core_sensor_device__828177_idx'),
        ),

        migrations.DeleteModel(
            name='AlertRule',
        ),
        migrations.DeleteModel(
            name='NotificationLog',
        ),
        migrations.AlterUniqueTogether(
            name='sensor',
            unique_together={('device', 'name')},
        ),
    ]
