# Generated by Django 4.2.26 on 2025-11-30 16:09

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_device_remove_notificationlog_alert_rule_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensor',
            name='last_value',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.CreateModel(
            name='ServiceLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('service_type', models.CharField(blank=True, max_length=200)),
                ('notes', models.TextField()),
                ('coldhead_hours', models.PositiveIntegerField(default=0)),
                ('compressor_hours', models.PositiveIntegerField(default=0)),
                ('adsorber_hours', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_logs', to='core.device')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
